# -*- coding: utf-8 -*-
"""Data-Twitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvmZqW-skh3JoMZfVAPBKTusY2FT9q28

Importar librerias
"""

#Instalación de paquetes
!pip install config
!pip install langdetect

#Importacion de librerias 
import tweepy
import datetime
import pandas as pd

#Utilizar las Credeciales de Twitter 
TWITTER_CONSUMER_KEY = 'XabZgmY0CvdnC80CIqukoEq5G'
TWITTER_CONSUMER_SECRET = 'SfZ95BhHw5zSQhqzbCF89lHC0GRNpzS15Zx0XK1dzsDXHsiTYj'
TWITTER_ACCESS_TOKEN = '1389193434909532160-92Xm44NHeBlFPjPb7EdQZ6TMIPDYs2'
TWITTER_ACCESS_TOKEN_SECRET= '4RhM83yaMr0wFFSzhCxH3IphaBsInhGkLLhYmg3M8kXej'

auth = tweepy.OAuthHandler(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET)
auth.set_access_token(TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET)
api = tweepy.API(auth,wait_on_rate_limit=True)

#Delimitar fechas entre hoy y ayer
today = datetime.date.today()
yesterday= today - datetime.timedelta(days=1)

tweets_list = tweepy.Cursor(api.search, q="#Tigo since:" + str(yesterday)+ " until:" + str(today),tweet_mode='extended', lang='es').items()

tweets_list

output = []
for tweet in tweets_list:
    text = tweet._json["full_text"]
    print(text)
    username = tweet.user.name
    location = tweet.user.location
    created_at = tweet.created_at
    favourite_count = tweet.favorite_count
    retweet_count = tweet.retweet_count
    
    
    line = {'Text' : text, 'User' : username, 'Location' : location, 'Created' : created_at ,'Favourite_count' : favourite_count, 'Retweet_count' : retweet_count}
    output.append(line)

df = pd.DataFrame(output)
df.to_csv('data.csv')

df